name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
          options : >-
            --health-cmd pg-isready
            --health-interval 20s
            --health-timeout 5s
            --health-retries 5

    steps:
    - uses: actions/checkout@v3

    -name: Run migrations
      run: make migrateup

    -name: Install goalng-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-386.tar.gz | tar xvz
        sudo mv migrate /user/bin/migrate
        which migrate

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    
    - name: Test
      run: make test
